### ISSUE TITLE
算能airbox上执行bmwhisper，出现Illegal instruction

### ISSUE THREAD

**Issue by loredunk** [JKay0327/whisper-TPU_py#7]
(.venv) linaro@bm1684:/data/whisper-TPU_py$ bmwhisper ./test/demo.wav --model base --bmodel_dir ./bmodel/ --chip_mode soc
Illegal instruction

下面是我的airbox配置，芯片是bm1684x，请问有什么思路嘛,调试了一下感觉是torch出现了问题，执行torch也会出现这样的报错，请问推荐什么版本的Torch？

(.venv) linaro@bm1684:/data/whisper-TPU_py$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       2
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     2300.0000
CPU min MHz:                     1150.0000
BogoMIPS:                        100.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpui
                                 d

**Comment by loredunk** [comment]
解决了，装Torch1.13就行

**Comment by JKay0327** [comment]
最新的torch会出现这个问题，降版本就可以解决。

**Comment by loredunk** [comment]
> 最新的torch会出现这个问题，降版本就可以解决。

我想额外请问一下，为什么whisper转录了都是繁体字。。

**Comment by JKay0327** [comment]
这个应该跟官方训练的权重有关系
